apiVersion: apps/v1
kind: Deployment
metadata:
  name: tbutil-chromedp
  labels:
    app: tbutil-chromedp
spec:
  replicas: 1

  selector:
    matchLabels:
      app: tbutil-chromedp

  template:

    metadata:
      labels:
        app: tbutil-chromedp

    spec:
      serviceAccountName: tbutil-chromedp-user

      securityContext:
        fsGroup: 2000

      containers:
      - name: tbutil-chromedp
        image: turbointegrations/tbutil-chromedp:2.0j
        imagePullPolicy: IfNotPresent
        env:
          - name: TURBO_MACHINE_ID_FILE
            value: /home/tbutil/.tbutilmachine-id

          - name: TURBO_K8S_SERVICE_NAME
            value: tbutil-chromedp

          # Set this to true to auto-configure volumes and mounts.
          #
          # Set to false to bye-pass auto-configuration. In this case
          # you will need to uncomment/edit the volumeMounts and volumes
          # sections below and create the tbutil-chromedp-volume PVC
          # before applying this yaml config.

          - name: TURBO_AUTOCONFIGURE_K8S
            value: "true"

          - name: TZ
            value: GMT
        ports:


# For trouble-shooting the boostratp, just uncomment these two lines (command
# and args). This causes the boostrap script to be bye-passed so that the pod
# starts and you can "exec" a shell to investigate the problem.

#        command: [ "/bin/sleep" ]
#        args: [ "infinity" ]


# If the auto-creation of volumes doesnt work (eg: not compatible with your cluster
# setup), then you will need to create the tbutil-chromedp-volume volume by hand and
# configure the "volumeMounts" and "volumes" sections for this deployment. Uncommenting
# the lines below could be a good starting point for the latter step.

#        volumeMounts:
#          - name: tbutil-chromedp-volume
#            subPath: tbutil
#            mountPath: /home/tbutil
#
#          - name: tbutil-chromedp-volume
#            subPath: tbexport
#            mountPath: /home/tbexport
#
#          - name: tbutil-chromedp-volume
#            subPath: etc-ssh
#            mountPath: /etc/ssh
#
#          - name: tbutil-chromedp-volume
#            subPath: etc-crontabs
#            mountPath: /etc/crontabs
#
#          - name: turbo-volume
#            mountPath: /etc/turbonomic
#

#      volumes:
#        - name: tbutil-chromedp-volume
#          persistentVolumeClaim:
#            claimName: tbutil-chromedp-volume
#
#        # NB: The confgMap name field below should match the existing config map. You can
#        # determine the needed name by using the command:
#        #     kubectl get configMap -n turbonomic | grep global-properties
#
#        - name: turbo-volume
#          configMap:
#            defaultMode: 420
#            name: global-properties-xl-example
#            optional: true
#

---

kind: ServiceAccount
apiVersion: v1
metadata:
  name: tbutil-chromedp-user

---

kind: ClusterRoleBinding

# For OpenShift 3.4-3.7 use apiVersion: v1
# For kubernetes 1.9 use rbac.authorization.k8s.io/v1
# For kubernetes 1.8 use rbac.authorization.k8s.io/v1beta1
apiVersion: rbac.authorization.k8s.io/v1

metadata:
  name: tbutil-chromedp-binding

subjects:
  - kind: ServiceAccount
    name: tbutil-chromedp-user
    namespace: turbonomic

roleRef:
  # User creating this resource must have permissions to add this policy to the SA
  kind: ClusterRole
  name: cluster-admin

  # For OpenShift v3.4 remove apiGroup line
  apiGroup: rbac.authorization.k8s.io
