apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tbutil-flexera-volume
  namespace: turbonomic
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: turbo-local-storage
  volumeMode: Filesystem

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv-tbutil-flexera-volume
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  local:
    path: /data/turbonomic/tbutil-flexera
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - node1
  persistentVolumeReclaimPolicy: Delete
  storageClassName: turbo-local-storage
  volumeMode: Filesystem
