apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tbutil-base-volume
  namespace: turbonomic
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  storageClassName: gluster-heketi
