apiVersion: apps/v1
kind: Deployment
metadata:
  name: tbutil-hotwarm
  labels:
    app: tbutil-hotwarm
spec:
  replicas: 1

  selector:
    matchLabels:
      app: tbutil-hotwarm

  template:

    metadata:
      labels:
        app: tbutil-hotwarm

    spec:
      serviceAccountName: turbo-user

      securityContext:
        fsGroup: 2000

      volumes:
        - name: tbutil-hotwarm-volume
          persistentVolumeClaim:
            claimName: tbutil-hotwarm-volume

        - name: turbo-volume
          configMap:
            defaultMode: 420
            name: global-properties-xl-example
            optional: true

      containers:
      - name: tbutil-hotwarm
        image: labdocker:5000/tbutil-hotwarm:2.0a
        imagePullPolicy: IfNotPresent
        env:
          - name: TURBO_MACHINE_ID_FILE
            value: /home/tbutil/.tbutilmachine-id

          - name: TURBO_K8S_SERVICE_NAME
            value: tbutil-hotwarm

        ports:

        volumeMounts:
          - name: tbutil-hotwarm-volume
            subPath: tbutil
            mountPath: /home/tbutil

          - name: tbutil-hotwarm-volume
            subPath: tbexport
            mountPath: /home/tbexport

          - name: tbutil-hotwarm-volume
            subPath: etc-ssh
            mountPath: /etc/ssh

          - name: tbutil-hotwarm-volume
            subPath: etc-crontabs
            mountPath: /etc/crontabs

          - name: turbo-volume
            mountPath: /etc/turbonomic

---
